### ISSUE TITLE
import not showing up after install

### ISSUE THREAD

**Issue by dvdcourage** [vvoovv/blender-srtm#2]
When I install the addon it says its installed but it is not showing up under file import
I have closed and reopened blender a couple of times but its still not showing up
Any Ideas

Cheers

**Comment by vvoovv** [comment]
Have you installed the addon as described in the [documentation](https://github.com/vvoovv/blender-terrain/wiki/Documentation#installation)?

**Comment by dvdcourage** [comment]
Hi Vladimir
I downloaded the file from github as .zip file
In blender I went to Edit-Prefrences-Addon
Install from file
Selected the downloaded .zip and installed
Then activated the addon Import Terrain .hgt

**Comment by vvoovv** [comment]
So does the addon work for you now?

**Comment by dvdcourage** [comment]
Hi Vladimir

No The addon still doesn’t show up in the file import menu

Kind Regards

David Courage

**Comment by vvoovv** [comment]
Which version of Blender do you use?

**Comment by dvdcourage** [comment]
HI Vladimir

Version: 2.80Beta
Date:2019-04-17 1926
Hash: b46245470f79
Branch: blender2.7

Kind Regards

David Courage

This communication may be a privileged communication you are not authorised to distribute without prior approval from the sender. If you are not the intended recipient, then you are not authorised to retain, copy or distribute it. Please notify the sender and delete the message in its entirety.

**Comment by vvoovv** [comment]
I haven't ported it to Blender 2.80. Please try it with Blender 2.79 or with my paid addon [blender-osm](https://gumroad.com/l/blender-osm).

**Comment by dvdcourage** [comment]
OK I will try with blender 2.79 tomorrow

**Comment by vvoovv** [comment]
@dvdcourage 
The addon has been finally ported to Blender 2.8x. Please download and install the latest version of the addon.
